language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: FSIKokiUbByjFaiGMXqKoeQXZgFenJVHdCVcWVLtQkM8C9WOb7Gm5zPCVr6p/GccADPHRITj3Gr+hhAt2x5Qe7H2k3SDQV1ywPtK6Sc0Xs/beBCQUOAVbau/ZzVw0A/aGuvfMh4XatCKjlpiIYtt48n3WTEnB0fcsAsQ/F28ScmpfxfgWhHQOCmcONtLKZuq1dfwQH33JsXyH6Y4W7NL64hfulNfTITwy3xcChcC3vgXl6oJxRzCtZwi/k4HNDhS+amhCEncMZwojmlkwKa4j5SFcnss7cXJ7vo5knTZNaw34MfCGn9xOLHxJWZho7M6KBesvHFym4/mfbs2k+AeYOyyfFVgR2i53JP1KPtEQzmAR6p2HnNbpwzeX4nuOYWQvXc6x5nd8bRT+DuQzLkoQn+mHzvl0EI3Pr4Tx08AsMtM/BwpX+HcgUTEa18yAy4l/9nUUNHTk+lUhznSU7VgoTmgAioa/jNtM+bfb37Rx1S8bszeFNE/K/ouEySblgjVfE2rJOqkTyhgUO/9bTAKJKuK1dA+5OOnBgD3DMchhjwBp8ftO3vUrxMpYOvd3UrfcuJhK0PdGrUn2Rt9i7O+SSMtq8ZJn81bgDvfBmm3EGszuJyqlLhIGEoZWakV4JSwLV/f1NlRQdb0hkC8/S99MJa8QcRj5mWaOufSGiAqKuo=
  file: "/home/travis/build/raphael-suter/ConsoleCalculator/target/ConsoleCalculator-0.0.1-SNAPSHOT.jar"
  on:
    repo: raphael-suter/ConsoleCalculator
